### ISSUE TITLE
Persisting options

### ISSUE THREAD

**Issue by timkelty** [pilwon/node-get-env#1]
Do you have a suggested way to persist `get-env` across multiple files?

E.g. using with `node-get-config`:

``` js
var env = require('get-env')({
  docker: 'docker',  // or 'DOCKER'
  test: ['test', 'testing'],  // or ['TEST', 'TESTING']
  prod: ['pr', 'prod', 'production']  // or ['PR', 'PROD', 'PRODUCTION']
});
```

``` js
require('get-config')(__dirname + '/config', env, function (err, config) {});
```

If I'm using that env across multiple files, obviously I don't want to have to repeat all the options again.
My first thought is to set `NODE_CONFIG` and `NODE_CONFIG_DIR` env vars, similar to https://github.com/lorenwest/node-config/wiki/Environment-Variables.

Any other ideas?

**Comment by pilwon** [comment]
@timkelty You can set up a separate config file (ex: `config.js`) that exports `get-config` loaded config object, and all other modules can require this file. It not only removes code duplication but also provides a single source of truth for everything related to config. Does this technique work for your project?

**Comment by timkelty** [comment]
That's pretty much what I came up after some thought too, thanks, I think that'll work!
