### ISSUE TITLE
Adding "test" to the list of pre-existing environments

### ISSUE THREAD

**Issue by kevgo** [pilwon/node-get-env#3]
I think "test" is pretty widespread, and this library should encourage people to write tests and make that easy.

**Comment by PixnBits** [comment]
I'm seeing different data on this
Some say [only `development` and `production` should be used](http://stackoverflow.com/a/16979503)
Strongloop mentions [`staging` in one place, and omits it in another](https://docs.strongloop.com/display/public/LB/Environment-specific+configuration) 😕 
(FWIW [I've asked Strongloop about it](https://twitter.com/pixnbits/status/750499700659204098))

Personally, I'm wary of testing w/NODE_ENV set to something other than what I'll run in production as [it affects code that's activated](http://apmblog.dynatrace.com/2015/07/22/the-drastic-effects-of-omitting-node_env-in-your-express-js-applications/).

**Comment by pilwon** [comment]
Closing this issue by supporting @PixnBits's research. Thanks @kevgo for your proposal-
